version: '3.1'

services:

  db:
    image: mysql/mysql-server:5.7.24
    command: --default-authentication-plugin=mysql_native_password --sql-mode="" --secure_file_priv="/tmp"
    volumes:
      - ./home/:/home/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1
